### ISSUE TITLE
Umlaut-Domains throw errors

### ISSUE THREAD

**Issue by Rilgamon** [gravatarphp/gravatar#16]
In Nextcloud I encountered a problem where Email-Address with an Umlaut (äöü - domains in germany allow those characters) are not recognized.
See https://github.com/nextcloud/mail/issues/1903

**Comment by sagikazarmark** [comment]
Under the hood we use `filter_var` to validate the email address.

[This](https://bugs.php.net/bug.php?id=65630) might be related (which suggests it's not a bug).

I honestly have no idea what's the standard these days for email addresses. On one hand we have IDN, on the other I've never seen an email address with accented characters (and the linked ticket suggests it's not supported by RFCs (thought it's five years old now)).

@gmponos can you take point on this?

**Comment by Rilgamon** [comment]
Thanks, I see the problem. And on the other hand I could not find informations how gravatar handles such emails. I'll mark it as closed.

**Comment by sagikazarmark** [comment]
Try this: urlencode the email address, then MD5 it. If it matches your gravatar image URL, it should work with this lib as well.
