### ISSUE TITLE
Release :)

### ISSUE THREAD

**Issue by mnapoli** [gravatarphp/gravatar#6]
A release of that package would be great too :)

**Comment by sagikazarmark** [comment]
Aye aye sir. 😄

**Comment by sagikazarmark** [comment]
Added a few more features, did some improvements, tagged an alpha release. Feedback is more than welcome.

**Comment by mnapoli** [comment]
:+1:

One feedback I would have is that there's too much choice: I don't see the point of the `StaticUrlBuilder` and `SingleUrlBuilder`? IMO keeping it simpler with `UrlBuilder` would be better. But that's my feeling ;)

**Comment by sagikazarmark** [comment]
Yeah, I am having the same feeling for some time. I simply don't remember why I created those, but I have this feeling that they had some purpose. But you are right, most likely I will get rid of them before the stable.

**Comment by sagikazarmark** [comment]
See #9

**Comment by mnapoli** [comment]
Awesome thanks!
